version: '3.1'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: my-crypto
      POSTGRES_PASSWORD: my-crypto
    ports:
      - 4020:5432
